In [1]:
#Assignment 7

In [2]:
#Q.1

In [4]:
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix=np.column_stack([x**(N-i-1) for i in range (N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [5]:
np.linalg.det(matrix)

287.9999999999977

In [7]:
#Q.2


In [13]:
List_a = [3,5,7,2,8,10,11,65,72,81,99,100,150]

moving_seq = 3
cummlative_sum , moving_average = [0],[]

def Moving_average_fun(List_a, moveing_seq): 
    N =  moving_seq 
    for i , j  in enumerate(List_a,1): 
        cummlative_sum.append(cummlative_sum[i-1] + j) 

        if i>=N: 
            moving_ave = round((cummlative_sum[i] - cummlative_sum[i-N])/N,2) 

            moving_average.append(moving_ave) 
    return (moving_average), len(moving_average) 

Result_fun = Moving_average_fun(List_a,moving_seq)

print ("----"*10)
print (" User defined List :-\n {} \n User Define Window Size :-\t {} ".format(List_a,moving_seq))
print ("----"*10)
print (" Result Using above defined Funtion :\t")
print (" Moving average value :\n",Result_fun[0])
print (" Moving average seques has :- {}, values".format(Result_fun[1]))
print ("----"*10)

----------------------------------------
 User defined List :-
 [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
 User Define Window Size :-	 3 
----------------------------------------
 Result Using above defined Funtion :	
 Moving average value :
 [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
 Moving average seques has :- 11, values
----------------------------------------


In [9]:
#Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 

In [10]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
